
<style>.rw-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:14px}.rw-tile{border:2px solid #cbd5d9;border-radius:10px;padding:14px;background:white;display:block}.rw-tile:has(input:checked){border-color:#16736c;background:#eaf7f4}.rw-tile img{width:100%;height:160px;object-fit:contain;background:#f5f7f8}.rw-missing{background:#f1f4f5;padding:35px 12px;text-align:center;color:#485c64}.rw-tile small{display:block}.rw-step{background:#eaf6f4;padding:20px;border-radius:12px;margin:15px 0}.rw-tile input{width:20px;height:20px}.rw-actions{position:sticky;bottom:0;background:#fff;padding:15px;border-top:2px solid #16736c;z-index:5}.rw-grid label{cursor:pointer}</style>
<h1>RET–AM reconciliation workshop</h1>
<p>Work together: RET checks the engineering specification; AM identifies the physical inventory. An AM approver saves the decision.</p>
<p><strong><?=count(array_intersect($ids,$approved))?> of <?=count($ids)?> pilot part definitions published</strong> · This is catalogue progress, not stock availability.</p>
<?php if($error):?><div class="alert alert-danger" role="alert"><?=am_workshop_h($error)?></div><?php endif?>
<?php if($message):?><div class="alert alert-success" role="status"><?=am_workshop_h($message)?></div><?php endif?>
<form method="get"><label for="rw-part">1. Choose a UGP requirement</label><select name="part" id="rw-part" class="form-select" onchange="this.form.submit()">
<?php foreach($parts as $pid=>$p):?><option value="<?=am_workshop_h($pid)?>" <?=$pid===$partId?'selected':''?>><?=am_workshop_h($p['name'])?><?=in_array($pid,$approved,true)?' — published':''?></option><?php endforeach?></select><button class="btn btn-outline-secondary mt-2">Open part</button></form>
<div class="rw-step"><h2><?=am_workshop_h($part['name'])?></h2><p><strong>Canonical part number:</strong> <?=am_workshop_h($partId)?></p><p><strong>Specification:</strong> <?=am_workshop_h($part['specification'])?></p><p><strong>Unit:</strong> <?=am_workshop_h($part['unit'])?></p><p>Reference captured 8 September 2026. RET must check the current UGP specification before publication. <a href="https://ugp.1pwrafrica.com/parts/<?=rawurlencode($partId)?>" target="_blank" rel="noopener">View this UGP part, assemblies and drawings</a></p></div>
<h2>2. Select the existing AM item(s)</h2><p>Specification suggestions include purchasing evidence reviewed on 14 September 2026. A quotation supports a possible specification; it does not prove this stock was received. Opening-stock entry dates are excluded. Use <strong>Prepare review</strong> to select a candidate and fill a draft; then check the stated question together.</p><p>Likely matches appear first. Select multiple records only if each is the same specified part. A similar name alone is insufficient. Search changes clear unsaved selections.</p>
<form method="get" class="mb-3"><input type="hidden" name="part" value="<?=am_workshop_h($partId)?>"><label for="rw-search">Search Lesotho inventory by name, manufacturer, model or tag</label><input class="form-control" name="q" id="rw-search" value="<?=am_workshop_h($q)?>"><button class="btn btn-outline-primary mt-2">Search inventory</button></form>
<p><?=count($shown)?> shown of <?=count($filtered)?> accessible items. <?=count($filtered)>count($shown)?'Use search to find other items in the inventory.':''?></p>
<form method="post" id="rw-decision"><input type="hidden" name="csrf" value="<?=am_workshop_h($_SESSION['am_receipt_csrf'])?>"><input type="hidden" name="event_id" value="<?=am_workshop_h($eventId)?>">
<div class="rw-grid">
<?php foreach($shown as $a): $aid=$a['id']??$a['asset_id'];$suggestion=am_workshop_evidence($a,$partId);$pictures=array_values(array_filter($media,fn($m)=>!empty($m['approved']) && (($m['asset_id']??'')===$aid || (!empty($a['definition_id']) && ($m['definition_id']??'')===$a['definition_id']))));?>
<div class="rw-tile"><label><input type="checkbox" name="asset_ids[]" value="<?=am_workshop_h($aid)?>" <?=in_array($aid,(array)($_POST['asset_ids']??[]),true)?'checked':''?>> <strong><?=am_workshop_h($a['name']??'Unnamed item')?></strong>
<?php if($pictures):?><img loading="lazy" src="../assets/reference-photo.php?id=<?=rawurlencode($pictures[0]['id'])?>" alt="<?=am_workshop_h($pictures[0]['caption'])?>"><?php else:?><div class="rw-missing">No reference photo yet</div><?php endif?>
<small><?=am_workshop_rank($a,$partId,$part)>=500?'Previously identified candidate — verify before selecting':'Inventory search result — not verified'?></small>
<p><?=am_workshop_h($a['description']??'No description recorded')?></p><small>Unit: <?=am_workshop_h($a['unit_of_measure']??'Unknown')?> · <?=am_workshop_h(($a['manufacturer']??'').' '.($a['model']??''))?></small><small>Location: <?=am_workshop_h($a['location_id']??'Unknown')?> · Recorded quantity: <?=am_workshop_h($a['quantity']??'Unknown')?></small><small>Tag: <?=am_workshop_h($a['asset_tag']??$aid)?></small></label>
<?php if($suggestion):?><div class="rw-step"><strong><?=am_workshop_h(['strong'=>'Strong specification candidate','candidate'=>'Possible match — one more check','difference'=>'Specification difference to resolve'][$suggestion['band']])?></strong><p><?=am_workshop_h($suggestion['reason'])?></p><p><strong>Check together:</strong> <?=am_workshop_h($suggestion['check'])?></p><small><?=am_workshop_h($suggestion['source'])?></small><button type="button" class="btn btn-outline-primary mt-2 rw-prepare" data-asset="<?=am_workshop_h($aid)?>" data-decision="<?=am_workshop_h($suggestion['decision'])?>" data-note="<?=am_workshop_h('DRAFT — not yet verified. '.$suggestion['reason'].' To verify: '.$suggestion['check'].' Source: '.$suggestion['source'].'. Purchasing evidence does not prove receipt.')?>">Prepare review of this item</button></div><?php endif?>
<a target="_blank" rel="noopener" href="../assets/view.php?id=<?=rawurlencode($aid)?>">Inspect item</a> · <a target="_blank" rel="noopener" href="../assets/reference-photo.php?asset=<?=rawurlencode($aid)?>">Add/view photos</a></div>
<?php endforeach?></div>
<?php if(!$shown):?><p class="alert alert-warning">No matching accessible inventory records. Clear the search, or record “No existing item found” below. This does not establish zero physical stock.</p><?php endif?>
<div class="rw-step"><h2>3. Agree and record the decision</h2>
<p id="rw-prepared" role="status" tabindex="-1"></p><label for="rw-ret">RET participant name (present in this workshop)</label><input id="rw-ret" class="form-control" name="ret_participant" required minlength="3" maxlength="120" value="<?=am_workshop_h($_POST['ret_participant']??$_SESSION['am_workshop_ret']??'')?>">
<p>The signed-in AM approver records this name and attestation. This is not a separate RET login or digital signature.</p>
<label for="rw-kind">Decision</label><select id="rw-kind" name="decision" class="form-select" required><option value="">Choose a decision</option><option value="same_part">Same part — publish canonical identity</option><option value="alternative">Possible approved alternative — engineering follow-up</option><option value="component">Component of assembly — define quantities and relationship</option><option value="not_match">Not a match — record rejected selections</option><option value="need_photo">Need a reference photo</option><option value="need_specification">Need a specification</option><option value="not_found">No existing item found</option></select>
<p><strong>Same part</strong> changes the selected AM names/descriptions to the UGP reference above, creates or reuses the shared part definition and retains old names as aliases. Quantities and ownership do not change. Alternatives and components create follow-up tasks; they are not published as identical parts.</p>
<label for="rw-note">Specification evidence / follow-up instructions</label><textarea id="rw-note" class="form-control" name="evidence" required minlength="20" maxlength="2000" rows="3"><?=am_workshop_h($_POST['evidence']??'')?></textarea><p>Example: “RET checked the manufacturer's 25–95 mm² conductor range; AM checked the store item and confirmed it is a complete clamp, not a component.” Only record checks actually performed.</p>
<fieldset><legend class="h5">Required to publish “Same part”</legend><label class="d-block"><input type="checkbox" name="current_specification_verified"> RET checked that the reference above matches the current UGP part.</label><label class="d-block"><input type="checkbox" name="ret_verified"> RET verified dimensions, rating, construction and unit for every selected item.</label><label class="d-block"><input type="checkbox" name="am_verified"> AM verified the physical item or reliable manufacturer evidence and agrees it is the same part.</label></fieldset>
<label for="rw-owner">Follow-up owner (required for unresolved decisions)</label><input id="rw-owner" name="owner_name" class="form-control" maxlength="120" value="<?=am_workshop_h($_POST['owner_name']??'')?>"><label for="rw-due">Due date</label><input id="rw-due" type="date" name="due_date" class="form-control" value="<?=am_workshop_h($_POST['due_date']??'')?>"><p>Agree the assignment with the owner. Saving does not send a notification.</p></div>
<div class="rw-actions"><button id="rw-save" class="btn btn-primary" type="submit">Save agreed decision</button> <a class="btn btn-outline-secondary" href="catalogue-tasks.php">Follow-up queue</a> <a class="btn btn-outline-secondary" href="reconciliation.php?part=<?=rawurlencode($ids[(array_search($partId,$ids)+1)%count($ids)])?>">Next part (does not save)</a></div></form>
<script>const choice=document.getElementById('rw-kind');choice.addEventListener('change',()=>{document.getElementById('rw-save').textContent=choice.value==='same_part'?'Publish shared identity':'Save agreed decision';for(const n of ['ret_verified','am_verified','current_specification_verified'])document.querySelector('[name="'+n+'"]').required=choice.value==='same_part';const followup=choice.value!==''&&!['same_part','not_match'].includes(choice.value);document.getElementById('rw-owner').required=followup;document.getElementById('rw-due').required=followup;});choice.value=<?=json_encode((string)($_POST['decision']??''), JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;choice.dispatchEvent(new Event('change'));</script>
<h2>Decision history</h2><?php if(!$history):?><p>No workshop decisions recorded for this part.</p><?php endif?>
<?php foreach(array_slice($history,0,12) as $r):?><div class="card p-3 mb-2"><strong><?=am_workshop_h(str_replace('_',' ',$r['decision']??''))?> · <?=am_workshop_h($r['created_at']??'')?></strong><p><?=am_workshop_h($r['evidence']??'')?></p><small>RET participant: <?=am_workshop_h($r['retParticipant']??'')?> · AM account: <?=am_workshop_h($r['actor']??'')?></small></div><?php endforeach?>
<p>After publication, capture new evidence in <a href="https://nexus.1pwrafrica.com/forecast">Nexus Forecast</a>. Existing snapshots stay unchanged.</p>


<script>
document.querySelectorAll('.rw-prepare').forEach(button=>button.addEventListener('click',()=>{
 const note=document.getElementById('rw-note');
 if(note.value.trim() && !window.confirm('Replace the unsaved note and item selections with this suggested review?'))return;
 document.querySelectorAll('[name="asset_ids[]"]').forEach(el=>el.checked=el.value===button.dataset.asset);
 for(const n of ['ret_verified','am_verified','current_specification_verified'])document.querySelector('[name="'+n+'"]').checked=false;
 choice.value=button.dataset.decision;choice.dispatchEvent(new Event('change'));note.value=button.dataset.note;
 const status=document.getElementById('rw-prepared');status.textContent='Draft prepared. Nothing has been saved. Check the evidence together, replace the draft with your findings, and complete the required confirmations before saving.';status.focus();status.scrollIntoView({behavior:'smooth',block:'center'});
}));
</script>
