<?php $paging ??= am_workshop_page($filtered, 1); $partIndex = array_search($partId, $ids); ?>

<style>.rw-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:14px}.rw-tile{border:2px solid #cbd5d9;border-radius:10px;padding:14px;background:white;display:block}.rw-tile:has(input:checked){border-color:#16736c;background:#eaf7f4}.rw-tile img{width:100%;height:160px;object-fit:contain;background:#f5f7f8}.rw-missing{background:#f1f4f5;padding:35px 12px;text-align:center;color:#485c64}.rw-tile small{display:block}.rw-step{background:#eaf6f4;padding:20px;border-radius:12px;margin:15px 0}.rw-tile input{width:20px;height:20px}.rw-actions{position:sticky;bottom:0;background:#fff;padding:15px;border-top:2px solid #16736c;z-index:5}.rw-grid label{cursor:pointer}</style>
<h1>RET–AM reconciliation workshop</h1>
<p>Work together: RET checks the engineering specification; AM identifies the physical inventory. An AM approver saves the decision.</p>
<p><strong><?=count(array_intersect($ids,$approved))?> of <?=count($ids)?> requirements linked to accessible AM records</strong> · This is catalogue progress, not stock availability.</p>
<?php if($error):?><div class="alert alert-danger" role="alert"><?=am_workshop_h($error)?></div><?php endif?>
<?php if($message):?><div class="alert alert-success" role="status"><?=am_workshop_h($message)?></div><?php endif?>
<?php include __DIR__.'/reconciliation_exceptions.php'; ?>
<p><strong>UGP requirement <?=($partIndex+1)?> of <?=count($ids)?></strong>. The tiles below are AM candidates for this one requirement.</p>
<nav aria-label="UGP requirements"><?php if($partIndex>0):?><a class="btn btn-outline-secondary rw-leave" href="<?=am_workshop_h(am_workshop_url($ids[$partIndex-1]))?>">Previous UGP requirement</a> <?php endif?><?php if($partIndex<count($ids)-1):?><a class="btn btn-outline-secondary rw-leave" href="<?=am_workshop_h(am_workshop_url($ids[$partIndex+1]))?>">Next UGP requirement (does not save)</a><?php endif?></nav>
<form method="get" class="rw-navigation"><label for="rw-part">1. Choose a UGP requirement</label><select name="part" id="rw-part" class="form-select" onchange="this.form.requestSubmit()">
<?php foreach($parts as $pid=>$p):?><option value="<?=am_workshop_h($pid)?>" <?=$pid===$partId?'selected':''?>><?=am_workshop_h($p['name'])?><?=in_array($pid,$approved,true)?' — published':''?></option><?php endforeach?></select><button class="btn btn-outline-secondary mt-2">Open part</button></form>
<div class="rw-step"><h2><?=am_workshop_h($part['name'])?></h2><p><strong>Canonical part number:</strong> <?=am_workshop_h($partId)?></p><p><strong>Specification:</strong> <?=am_workshop_h($part['specification'])?></p><p><strong>Unit:</strong> <?=am_workshop_h($part['unit'])?></p><p>Reference captured 8 September 2026. RET must check the current UGP specification before publication. <a href="https://ugp.1pwrafrica.com/parts/<?=rawurlencode($partId)?>" target="_blank" rel="noopener">View this UGP part, assemblies and drawings</a></p></div>
<h2>2. Select the existing AM item(s)</h2><p>Specification suggestions include purchasing evidence reviewed on 14 September 2026. A quotation supports a possible specification; it does not prove this stock was received. Opening-stock entry dates are excluded. Use <strong>Prepare review</strong> to select a candidate and fill a draft; then check the stated question together.</p><p>Likely matches appear first. Select multiple records only if each is the same specified part. A similar name alone is insufficient. Search changes clear unsaved selections.</p>
<form method="get" class="mb-3 rw-navigation"><input type="hidden" name="part" value="<?=am_workshop_h($partId)?>"><label for="rw-search">Search Lesotho inventory by name, manufacturer, model or tag</label><input class="form-control" name="q" id="rw-search" value="<?=am_workshop_h($q)?>"><button class="btn btn-outline-primary mt-2">Search inventory</button></form>
<p><strong>AM candidates <?=count($filtered)?$paging['offset']+1:0?>–<?=$paging['offset']+count($shown)?> of <?=count($filtered)?></strong> · Page <?=$paging['page']?> of <?=$paging['pages']?>. These are inventory options, not completed mappings. Search to narrow the list.</p>
<?php include __DIR__.'/reconciliation_paging.php'; ?>
<p>After adding photos, return to this review, select the correct AM item and save the agreed decision with RET. A photo alone does not link the item. To work on a different UGP part, use <strong>Next UGP requirement</strong> or the selector above.</p>
<form method="post" id="rw-decision"><input type="hidden" name="csrf" value="<?=am_workshop_h($_SESSION['am_receipt_csrf'])?>"><input type="hidden" name="event_id" value="<?=am_workshop_h($eventId)?>">
<div class="rw-grid">
<?php foreach($shown as $a): $aid=$a['id']??$a['asset_id'];$suggestion=am_workshop_evidence($a,$partId);$original=am_workshop_original($a,$allReviews);$block=am_workshop_block($partId,$aid);$pictures=array_values(array_filter($media,fn($m)=>!empty($m['approved']) && (($m['asset_id']??'')===$aid || (!empty($a['definition_id']) && ($m['definition_id']??'')===$a['definition_id']))));?>
<div class="rw-tile"><label><input type="checkbox" name="asset_ids[]" value="<?=am_workshop_h($aid)?>" data-name="<?=am_workshop_h($a['name']??'Unnamed item')?>" data-tag="<?=am_workshop_h($a['asset_tag']??$aid)?>" data-original="<?=am_workshop_h($original['description']??'No original description')?>" data-block="<?=am_workshop_h($block??'')?>" <?=in_array($aid,(array)($_POST['asset_ids']??[]),true)?'checked':''?>> <strong><?=am_workshop_h($a['name']??'Unnamed item')?></strong>
<?php if($pictures):?><img loading="lazy" src="../assets/reference-photo.php?id=<?=rawurlencode($pictures[0]['id'])?>" alt="<?=am_workshop_h($pictures[0]['caption'])?>"><?php else:?><div class="rw-missing">No reference photo yet</div><?php endif?>
<small><?=am_workshop_rank($a,$partId,$part)>=500?'Previously identified candidate — verify before selecting':'Inventory search result — not verified'?></small>
<p><strong>AM recorded description:</strong> <?=am_workshop_h($a['description']??'No description recorded')?></p><details><summary>Original AM identity (before reconciliation)</summary><p><?=am_workshop_h($original['name']??'')?> — <?=am_workshop_h($original['description']??'No description recorded')?></p></details><?php if($block):?><p class="alert alert-warning"><strong>Cannot publish as this part:</strong> <?=am_workshop_h($block)?> You can still record an alternative, component or rejected match.</p><?php endif?><small>Unit: <?=am_workshop_h($a['unit_of_measure']??'Unknown')?> · <?=am_workshop_h(($a['manufacturer']??'').' '.($a['model']??''))?></small><small>Location: <?=am_workshop_h($a['location_id']??'Unknown')?> · Recorded quantity: <?=am_workshop_h($a['quantity']??'Unknown')?></small><small>Tag: <?=am_workshop_h($a['asset_tag']??$aid)?></small></label>
<?php if($suggestion):?><div class="rw-step"><strong><?=am_workshop_h(['strong'=>'Strong specification candidate','candidate'=>'Possible match — one more check','difference'=>'Specification difference to resolve'][$suggestion['band']])?></strong><p><?=am_workshop_h($suggestion['reason'])?></p><p><strong>Check together:</strong> <?=am_workshop_h($suggestion['check'])?></p><small><?=am_workshop_h($suggestion['source'])?></small><button type="button" class="btn btn-outline-primary mt-2 rw-prepare" data-asset="<?=am_workshop_h($aid)?>" data-decision="<?=am_workshop_h($suggestion['decision'])?>" data-note="<?=am_workshop_h('DRAFT — not yet verified. '.$suggestion['reason'].' To verify: '.$suggestion['check'].' Source: '.$suggestion['source'].'. Purchasing evidence does not prove receipt.')?>">Prepare review of this item</button></div><?php endif?>
<a target="_blank" rel="noopener" href="../assets/view.php?id=<?=rawurlencode($aid)?>">Inspect item</a> · <a target="_blank" rel="noopener" href="../assets/reference-photo.php?asset=<?=rawurlencode($aid)?>&amp;part=<?=rawurlencode($partId)?>&amp;page=<?=$paging['page']?>&amp;q=<?=rawurlencode($q)?>">Add/view photos</a></div>
<?php endforeach?></div>
<?php include __DIR__.'/reconciliation_paging.php'; ?>
<?php if(!$shown):?><p class="alert alert-warning">No matching accessible inventory records. Clear the search, or record “No existing item found” below. This does not establish zero physical stock.</p><?php endif?>
<div class="rw-step"><h2>3. Agree and record the decision</h2>
<p id="rw-prepared" role="status" tabindex="-1"></p><label for="rw-ret">RET participant name (present in this workshop)</label><input id="rw-ret" class="form-control" name="ret_participant" required minlength="3" maxlength="120" value="<?=am_workshop_h($_POST['ret_participant']??$_SESSION['am_workshop_ret']??'')?>">
<p>The signed-in AM approver records this name and attestation. This is not a separate RET login or digital signature.</p>
<label for="rw-kind">Decision</label><select id="rw-kind" name="decision" class="form-select" required><option value="">Choose a decision</option><option value="same_part">Same part — publish canonical identity</option><option value="alternative">Possible approved alternative — engineering follow-up</option><option value="component">Component of assembly — define quantities and relationship</option><option value="not_match">Not a match — record rejected selections</option><option value="need_photo">Need a reference photo</option><option value="need_specification">Need a specification</option><option value="not_found">No existing item found</option></select>
<p><strong>Same part</strong> links the selected AM items to the UGP name and number. Original AM descriptions stay intact, old names remain aliases, and the shared definition holds the engineering specification. Quantities and ownership do not change. Alternatives and components create follow-up tasks; they are not published as identical parts.</p>
<label for="rw-note">Specification evidence / follow-up instructions</label><textarea id="rw-note" class="form-control" name="evidence" required minlength="20" maxlength="2000" rows="3"><?=am_workshop_h($_POST['evidence']??'')?></textarea><p>Example: “RET checked the manufacturer's 25–95 mm² conductor range; AM checked the store item and confirmed it is a complete clamp, not a component.” Only record checks actually performed.</p>
<section class="card p-3 my-3" aria-labelledby="rw-comparison-heading"><h3 id="rw-comparison-heading">Compare before publishing</h3><p><strong>UGP requirement:</strong> <?=am_workshop_h($part['name'])?> · <?=am_workshop_h($partId)?></p><p><?=am_workshop_h($part['specification'])?></p><div id="rw-comparison" aria-live="polite">Select an AM item above to compare its original description here.</div><label for="rw-confirm-part">Confirm the requirement these selected items satisfy</label><select id="rw-confirm-part" name="confirmed_part_id" class="form-select"><option value="">Choose only after comparing the specifications</option><option value="<?=am_workshop_h($partId)?>"><?=am_workshop_h($part['name'].' — '.$partId)?></option></select><p>Example: a spindle alone is a component of an insulator assembly. Choose “Component of assembly”, not “Same part”.</p></section>
<fieldset><legend class="h5">Required to publish “Same part”</legend><label class="d-block"><input type="checkbox" name="current_specification_verified"> RET checked that the reference above matches the current UGP part.</label><label class="d-block"><input type="checkbox" name="ret_verified"> RET verified dimensions, rating, construction and unit for every selected item.</label><label class="d-block"><input type="checkbox" name="am_verified"> AM verified the physical item or reliable manufacturer evidence and agrees it is the same part.</label></fieldset>
<label for="rw-owner">Follow-up owner (required for unresolved decisions)</label><input id="rw-owner" name="owner_name" class="form-control" maxlength="120" value="<?=am_workshop_h($_POST['owner_name']??'')?>"><label for="rw-due">Due date</label><input id="rw-due" type="date" name="due_date" class="form-control" value="<?=am_workshop_h($_POST['due_date']??'')?>"><p>Agree the assignment with the owner. Saving does not send a notification.</p></div>
<div class="rw-actions"><button id="rw-save" class="btn btn-primary" type="submit">Save agreed decision</button> <a class="btn btn-outline-secondary" href="catalogue-tasks.php">Follow-up queue</a> <?php if($partIndex<count($ids)-1):?><a class="btn btn-outline-secondary rw-leave" href="<?=am_workshop_h(am_workshop_url($ids[$partIndex+1]))?>">Next UGP requirement (does not save)</a><?php else:?><span>Last UGP requirement — use the selector to revisit another part.</span><?php endif?></div></form>
<script>const choice=document.getElementById('rw-kind');choice.addEventListener('change',()=>{document.getElementById('rw-save').textContent=choice.value==='same_part'?'Publish shared identity':'Save agreed decision';for(const n of ['ret_verified','am_verified','current_specification_verified'])document.querySelector('[name="'+n+'"]').required=choice.value==='same_part';document.getElementById('rw-confirm-part').required=choice.value==='same_part';const followup=choice.value!==''&&!['same_part','not_match'].includes(choice.value);document.getElementById('rw-owner').required=followup;document.getElementById('rw-due').required=followup;});choice.value=<?=json_encode((string)($_POST['decision']??''), JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;choice.dispatchEvent(new Event('change'));</script>
<h2>Decision history</h2><?php if(!$history):?><p>No workshop decisions recorded for this part.</p><?php endif?>
<?php foreach(array_slice($history,0,12) as $r):?><div class="card p-3 mb-2"><strong><?=am_workshop_h(str_replace('_',' ',$r['decision']??''))?> · <?=am_workshop_h($r['created_at']??'')?></strong><?php if(!empty($r['publication_revoked_at'])):?><p class="alert alert-warning">Publication withdrawn: <?=am_workshop_h($r['publication_revocation_reason']??'')?>. This decision does not count as a current match.</p><?php endif?><p><?=am_workshop_h($r['evidence']??'')?></p><small>RET participant: <?=am_workshop_h($r['retParticipant']??'')?> · AM account: <?=am_workshop_h($r['actor']??'')?></small></div><?php endforeach?>
<p>After publication, capture new evidence in <a href="https://nexus.1pwrafrica.com/forecast">Nexus Forecast</a>. Existing snapshots stay unchanged.</p>


<script>
document.querySelectorAll('.rw-prepare').forEach(button=>button.addEventListener('click',()=>{
 const note=document.getElementById('rw-note');
 if(note.value.trim() && !window.confirm('Replace the unsaved note and item selections with this suggested review?'))return;
 document.querySelectorAll('[name="asset_ids[]"]').forEach(el=>el.checked=el.value===button.dataset.asset);
 for(const n of ['ret_verified','am_verified','current_specification_verified'])document.querySelector('[name="'+n+'"]').checked=false;
 choice.value=button.dataset.decision;choice.dispatchEvent(new Event('change'));note.value=button.dataset.note;
 const status=document.getElementById('rw-prepared');status.textContent='Draft prepared. Nothing has been saved. Check the evidence together, replace the draft with your findings, and complete the required confirmations before saving.';status.focus();status.scrollIntoView({behavior:'smooth',block:'center'});
}));
</script>

<script>
// Browsing is not a save. Confirm before discarding a review that has been edited.
const reviewForm=document.getElementById('rw-decision');let reviewDirty=false;
reviewForm.addEventListener('input',()=>reviewDirty=true);reviewForm.addEventListener('change',()=>reviewDirty=true);
document.querySelectorAll('.rw-prepare').forEach(b=>b.addEventListener('click',()=>reviewDirty=true));
const canLeave=()=>!reviewDirty||window.confirm('This review has unsaved selections or notes. Leave without saving? Uploaded photos are already saved.');
document.querySelectorAll('.rw-leave').forEach(a=>a.addEventListener('click',e=>{if(!canLeave())e.preventDefault();}));
document.querySelectorAll('.rw-navigation').forEach(f=>f.addEventListener('submit',e=>{if(!canLeave())e.preventDefault();}));
</script>

<script>
const comparison=document.getElementById('rw-comparison');
function updateComparison(){
 comparison.replaceChildren();
 const selected=[...document.querySelectorAll('[name="asset_ids[]"]:checked')];
 if(!selected.length)comparison.textContent='Select an AM item above to compare its original description here.';
 for(const item of selected){const p=document.createElement('p');p.textContent=item.dataset.name+' ('+item.dataset.tag+'): '+item.dataset.original;comparison.append(p);if(item.dataset.block){const warning=document.createElement('p');warning.className='alert alert-danger';warning.textContent='Cannot publish as the same part: '+item.dataset.block;comparison.append(warning);}}
 document.getElementById('rw-save').disabled=choice.value==='same_part'&&(!selected.length||selected.some(x=>x.dataset.block));
}
document.querySelectorAll('[name="asset_ids[]"]').forEach(el=>el.addEventListener('change',()=>{document.getElementById('rw-confirm-part').value='';for(const n of ['ret_verified','am_verified','current_specification_verified'])document.querySelector('[name="'+n+'"]').checked=false;updateComparison();}));
choice.addEventListener('change',updateComparison);
document.querySelectorAll('.rw-prepare').forEach(b=>b.addEventListener('click',()=>{document.getElementById('rw-confirm-part').value='';updateComparison();}));
document.getElementById('rw-start-question')?.addEventListener('click',e=>{const b=e.currentTarget,note=document.getElementById('rw-note');if(note.value.trim()&&!confirm('Replace your unsaved note with this question?'))return;note.value=b.dataset.note;choice.value=b.dataset.decision;choice.dispatchEvent(new Event('change'));reviewDirty=true;note.focus();note.scrollIntoView({behavior:'smooth',block:'center'});});
updateComparison();
</script>
