<section class="rw-step" aria-labelledby="rw-queue-title">
<details class="mb-3"><summary><strong>How to complete a review — guide and examples</strong></summary>
<ol><li>Choose <strong>Review this requirement</strong> below. Read its question and involve RET if a design choice is needed.</li><li>Read the uGP specification, then search the AM tiles. Open the original AM description, item record and photos.</li><li>Select the relevant item. The comparison below repeats both identities. A photo alone does not establish a match.</li><li>Choose <strong>Same part</strong> only when dimensions, rating and completeness agree. Confirm the requirement, name the RET participant present and record the checks actually performed.</li><li>For a 380mm bolt against a 200mm requirement, choose <strong>Possible alternative</strong>. For a spindle against an insulator assembly, choose <strong>Component of assembly</strong>. Specify what RET must decide, an agreed owner and a due date.</li><li>Save the decision, then open the next unresolved requirement. Follow-up decisions appear in the follow-up queue; they do not count as completed links or send a notification.</li></ol>
<p>Publication keeps the original AM description. Quantities and ownership do not change. AM-only supplies need no uGP link. After publication, capture a new Forecast snapshot; existing snapshots stay unchanged.</p></details>
<h2 id="rw-queue-title">Work still to resolve</h2>
<p>Start with a question below. AM finds the recorded item; RET resolves engineering differences. A similar name is not evidence of the same specification. Items already linked are automatically removed from this queue for your accessible inventory.</p>
<details <?=isset($_GET['queue'])?'open':''?>><summary><?=count($pendingIds)?> requirements need attention — open the guided queue</summary>
<div class="table-responsive"><table class="table"><thead><tr><th>Requirement</th><th>Who to involve</th><th>What to check next</th><th>Action</th></tr></thead><tbody>
<?php foreach($pendingIds as $pid):$g=$exceptionGuide[$pid]??['owner'=>'AM + RET','question'=>'Locate the matching AM item and verify its specification.'];?><tr><td><?=am_workshop_h($parts[$pid]['name'])?></td><td><?=am_workshop_h($g['owner'])?></td><td><?=am_workshop_h($g['question'])?></td><td><a class="btn btn-outline-primary rw-leave" href="<?=am_workshop_h(am_workshop_url($pid))?>">Review this requirement</a></td></tr><?php endforeach?>
</tbody></table></div></details>
<?php if(in_array($partId,$pendingIds,true) && isset($exceptionGuide[$partId])):$g=$exceptionGuide[$partId];?><h3>For this requirement: <?=am_workshop_h($part['name'])?></h3><p><strong>Work with <?=am_workshop_h($g['owner'])?>:</strong> <?=am_workshop_h($g['question'])?></p><p>Find evidence that answers this question. If it is a different specification, save “Possible alternative”; if it is one piece of a kit, save “Component of assembly”. Neither counts as a completed match.</p><button type="button" class="btn btn-outline-primary" id="rw-start-question" data-note="<?=am_workshop_h('Question to resolve: '.$g['question'].' Findings: ')?>" data-decision="<?=am_workshop_h($g['decision'])?>">Start a follow-up for this question</button>
<?php elseif(in_array($partId,$approved,true)):?><p><strong>This requirement already has a published inventory link.</strong> Review further entries only if necessary; do not repeat the completed check.</p><?php endif?>
<?php $nextPending=array_values(array_diff($pendingIds,[$partId]));if($nextPending):?><p><a class="btn btn-primary rw-leave" href="<?=am_workshop_h(am_workshop_url($nextPending[0]))?>">Open next unresolved requirement</a></p><?php endif?>
</section>
