<section class="card p-4 my-4" id="ret-am-workshop">
<h2>RET–AM workshop: turn existing inventory into shared parts</h2>
<p>An AM approver hosts the session, with a RET colleague beside them. Open <a href="<?=base_url('admin/reconciliation.php')?>">RET–AM workshop</a> in the sidebar. Start with the 36 MAS requirements; AM-only supplies stay outside this exercise.</p>
<ol><li><strong>Choose a UGP part.</strong> Read its specification and unit. RET checks the current UGP definition; the on-screen reference is dated 8 September 2026.</li>
<li><strong>Select AM tiles.</strong> Inspect the item, manufacturer and rating. Search other names or tags if the suggested tiles are wrong. “No reference photo yet” is a capture opportunity, not evidence that an item is absent.</li>
<li><strong>Agree the outcome.</strong> “Same part” requires all three checks and publishes the shared UGP number/name onto selected AM records. Alternatives and assemblies require follow-up; they are not identical parts.</li>
<li><strong>Record the evidence.</strong> Enter the RET participant’s name. The signed-in AM approver takes responsibility for the saved attestation; this is not a separate RET signature.</li>
<li><strong>Save, then move on.</strong> Give unresolved work an owner and due date. Agree it with them—no notification is sent automatically. “Next part” does not save.</li>
<li><strong>Refresh Forecast.</strong> Capture new inputs after publication. Historical snapshots stay unchanged.</li></ol>
<details><summary>Practice example: clamp or component?</summary><p>UGP calls for a complete 25–95 mm² ABC dead-end clamp. An AM tile describes only the steel bracket. Choose <strong>Component of assembly</strong>, give the engineering follow-up an owner/date, and describe the missing wedge and quantity relationship. Do not publish it as the complete clamp.</p></details>
<h3>Capture a useful photo once</h3><p>Use <strong>Add/view photos</strong> on the tile. The approver can choose or take a JPEG, PNG or WebP up to 5 MB, preview it, write a caption and approve it. Capture the complete item and a marking close-up if needed. Avoid people and private paperwork. Approved images follow the shared part definition across countries; they do not prove receipt or stock.</p>
<p>Give the first useful reference set contributor credit during the operations meeting. Prioritize parts blocking this workshop. Reuse existing images; do not reward duplicate uploads or require each country to photograph the same verified part again. No financial reward scheme is enabled.</p>
<details><summary>Guide rapide en français</summary><p>Un approbateur AM anime l’atelier avec un collègue RET. Choisissez une pièce UGP, vérifiez la spécification actuelle, puis sélectionnez les fiches AM correspondantes. « Same part » publie le numéro et la description communs après vérification. Une alternative ou un composant reste une tâche à résoudre, avec un responsable et une échéance. L’enregistrement ne transmet aucune notification. Ajoutez une photo de référence utile, puis réutilisez-la dans les autres pays. Les quantités de stock restent distinctes.</p></details>
</section>
